In [ ]:
import pandas as pd
import numpy as np

Ques 2:

In [29]:
def movingAvergae(arr,k,n):
  y= []
  sum =0
  for i in range(n-k+1):
    y.append(np.sum([arr[i:i+k]])/k)
  print(y)

arr = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
print(arr)
n = arr.shape[0]
movingAvergae(arr,3,n)


[  3   5   7   2   8  10  11  65  72  81  99 100 150]
[5.0, 4.666666666666667, 5.666666666666667, 6.666666666666667, 9.666666666666666, 28.666666666666668, 49.333333333333336, 72.66666666666667, 84.0, 93.33333333333333, 116.33333333333333]


Ques 1 : VANDER() Function


In [84]:
def myvander(arr,n,inc):
  result = np.mat([[0 for i in range(5)] for j in range(5)])
  for i in range(n):
    for j in range(4,-1,-1):
      res = arr[i] ** j
      if inc is True:
        result[i:i+1,j:j+1] = res
      else:
        result[i:i+1,n-j-1:n-j] = res
     
  print(result)
    



In [85]:
arr = np.array([1,2,3,4,5])
isincreasing = 'False'
n = arr.shape[0]
myvander(arr,n,isincreasing)

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]
